[16기 김건희] find user account 및 temporary password 관련 View
wecode-bootcamp-korea/tsunami-backend pull request #8
Opened 2021-01-18 07:56 UTC by konh2e

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 임시 비밀번호 찾기 관련 뷰 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 가입자 이름과, 이메일을 이용한 유저 정보 찾기 뷰
- 유저이름(ID), 이메일, 가입자 이름을 기반으로 한 임시 비밀번호 생성 뷰 
- `sign up`시 `birthday` 에 빈 스트링 인풋시 에러 핸들링을 위한 `None` 할당 코드 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-19 02:38 UTC, lordmyshepherd requested changes

2021-01-19 02:38 UTC, lordmyshepherd commented on users/views.py
> +            forgotten_user = User.objects.filter(name=name, email=email)
email도 같이 조회하는 이유가 있으신가요?

2021-01-19 02:38 UTC, lordmyshepherd commented on users/views.py
> +class FindUsernameView(View):
해당 View는 email과 name으로 user가 존재하는지 확인하는 엔드포인트 인가요?

2021-01-19 02:38 UTC, lordmyshepherd commented on users/views.py
> +            forgotten_user = User.objects.filter(name=name, email=email)
`forgotten_user`라는 의미는 무엇인가요?

2021-01-19 02:38 UTC, lordmyshepherd commented on users/views.py
> +        except TypeError:
TypeError는 언제 발생할 수 있나요?

2021-01-19 02:38 UTC, lordmyshepherd commented on users/views.py
> +                "USERNAME"  : forgotten_user.username[:-3]+ "*" * 3,
반환되는 username은 어떤 형태인가요?

2021-01-19 02:38 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'PASSWORD': random_password}, status=201)
임시 비밀번호를 응답으로 보내주는 이유가 있으신가요?

2021-01-19 02:38 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'PASSWORD': random_password}, status=201)
새로운 자원이 생성된 경우가 아니라 업데이트된 경우이므로 `status=200`이 더 정확합니다.
```suggestion
            return JsonResponse({'PASSWORD': random_password}, status=201)
```

2021-01-19 02:38 UTC, lordmyshepherd commented on users/views.py
> +        except TypeError:
typeError는 어떤 경우에 발생하나요?

2021-01-19 02:38 UTC, lordmyshepherd commented on users/views.py
> +            )
`Model의 objects manager class`의 `filter method`는 QuerySet을 반환합니다. 그렇기 때문에 변수명을 복수명사로 수정해주시면 좋을 것 같습니다.
```suggestion
            users = User.objects.filter(
                username = username, 
                name     = name, 
                email    = email
            )
```

2021-01-19 02:38 UTC, lordmyshepherd commented on users/views.py
> +            forgotten_user.save()
아래와 같이 수정해보시면 어떨까요?
`filter()`로 db 레코드를 조회할 때 database에 요청을 보내고 QuerySet을 반환받습니다. 이후에 `filter().exists()`로 method chaining할 때, 다시한번 db를 조회합니다. (hitting한다고 합니다.) 

2번 데이터베이스를 조회한다고 하면 아래와 같은 방법이 훨씬 효율적인 방법일 것입니다.
존재 여부부터 판단하고 존재하지 않으면 이후 db에 요청을 보내지 않겠죠?

```suggestion
            if User.objects.filter(username = username, name = name, email = email).exists():
                user = User.objects.get(username = username, name = name, email = email)
                random_password = token_urlsafe()[:16]
                user.password = bcrypt.hashpw(random_password.encode('utf-8'), bcrypt.gensalt()).decode("utf-8")
                user.save()
                return JsonResponse({'PASSWORD': random_password}, status=201)
            return JsonResponse({'MESSAGE': 'WRONG_USER'}, status=400)
```

2021-01-19 04:53 UTC, konh2e commented on users/views.py
> +            forgotten_user = User.objects.filter(name=name, email=email)
해당 뷰는 가입된 유저가 자신의 계정 정보를 잊었을때, 유저정보의 가입시 이름과, 이메일 주소를 통해 ,가입자 정보를 확인하는 기능입니다. 따라서 이름과, 이메일 정보를 같이 요구하도록 작성하였습니다.

2021-01-19 04:54 UTC, konh2e commented on users/views.py
> +class FindUsernameView(View):
해당 뷰는 email과 name을 통해서 자신이 기존에 가입했던 정보 (즉 잊어버린 유저네임) 를 확인하는 엔드포인트를 작성하고자 하였습니다.

2021-01-19 04:54 UTC, konh2e commented on users/views.py
> +            forgotten_user = User.objects.filter(name=name, email=email)
`user`라는 이름보다는 의미적으로 자신의 정보를 잊어버렸다는 의미에서 `forgotten_userername`을 찾고자 하는 `forgotten_user`라는 변수명을 사용했습니다.

2021-01-19 04:57 UTC, konh2e commented on users/views.py
> +        except TypeError:
`utils` 모듈에 작성된 정규 표현식을 이용한 함수를 사용해서 `email`을 `validation` 할 때 처음 키값에 해당하는 해쉬값이 의도되지 않은 타입(예를들어 email에 해당하는 키값의 타입이 int ) 인 경우에 발생하여 따로 핸들링하기로 하였습니다.

2021-01-19 04:59 UTC, konh2e commented on users/views.py
> +                "USERNAME"  : forgotten_user.username[:-3]+ "*" * 3,
유저가 자신의 잊어버린 유저네임을 확인하고자 할때, 보안 차원에서 뒷자리를 의도적으로 가리기 위해서 작성하였습니다. 따라서 위의 경우에서는 가입된 유저정보가 예를들어 `konh2e`라면  `kon***`와 같은 형태로 반환하게 됩니다.

2021-01-19 04:59 UTC, konh2e commented on users/views.py
> +            return JsonResponse({'PASSWORD': random_password}, status=201)
현재 작성된 코드에서는 임시 비밀번호를 응답으로 보냈지만 추가 기능을 구현해서 이메일로 발송하는 것으로 수정하려고 하는 중입니다.

2021-01-19 04:59 UTC, konh2e commented on users/views.py
> +            return JsonResponse({'PASSWORD': random_password}, status=201)
감사합니다!!!

2021-01-19 05:00 UTC, konh2e commented on users/views.py
> +            forgotten_user.save()
알려주셔서 고맙습니다 :D

2021-01-20 11:36 UTC, lordmyshepherd commented on users/views.py
> +                "USERNAME"  : forgotten_user.username[:-3]+ "*" * 3,
public api에서 사용자의 이름을 가려서 뿌려주시는 것은 정말 👍

2021-01-20 11:37 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'PASSWORD': random_password}, status=201)
네 건희님! 이후에 이메일로 발송하는 방향으로 수정 예정이라고 하시니 👍

2021-01-20 11:38 UTC, lordmyshepherd commented
LGTM 👍

2021-01-20 11:38 UTC, merged