[16기 장준영]Add: products_detail views.py 추가
wecode-bootcamp-korea/tsunami-backend pull request #9
Opened 2021-01-18 14:47 UTC by FreshTuna

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- products detail 페이지 views.py 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- product deatail 페이지 엔드 포인트를 위한 views.py 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- list view를 변경하는데 좋은 방법이 생각이 안납니다..

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-18 14:51 UTC, FreshTuna commented
소헌님! 아까 팀 미팅 때 해주신 조언대로 product list view를 변경하려고 했으나, 막상 구현 하려고 하니까 로직이 잘 떠오르질 않네요... ㅠㅠㅠ

2021-01-19 02:54 UTC, lordmyshepherd requested changes

2021-01-19 02:54 UTC, lordmyshepherd commented on products/views.py
>  class ProductListView(View):
Class명을 잘 만들어주셨습니다.

2021-01-19 02:54 UTC, lordmyshepherd commented on products/views.py
> +            nibs        = product.productthickness_set.all()
`line 63~ line 68` 코드에서, list comprehension 표현식이 실행될 때 body_color에서 참조하고 있는 다른테이블에 레코드를 읽어올 때 많은 수의 database hit가 일어날 것 같습니다.

이를 해결하기 위해서 `Model의 objects manager class`의 `method` 중에 `prefetch_related()`를 적용해보시면 좋을 것 같습니다.

2021-01-19 09:58 UTC, FreshTuna commented on products/views.py
>  class ProductListView(View):
피드백 감사합니다!

2021-01-19 16:19 UTC, FreshTuna commented on products/views.py
> +            nibs        = product.productthickness_set.all()
적용해보았습니다! 26번에서 13번으로 대략 반절 줄여보았어요.

2021-01-20 02:05 UTC, soheon-lee commented on products/views.py
> +                          'productthickness_set__thickness','productinkcolor_set__color','product_keyword','productoption_set').get(id=product_id)
gooood!
ㅎㅎ 차이 잘 파악하셨나요?

2021-01-20 02:05 UTC, soheon-lee commented on products/views.py
> +            # colors      = Colors.objects.prefetch_related('').all()
사용하지 않는 속성이라면 주석처리보다는 깔끔하게 지워주시면 감사하겠습니다 :)

2021-01-20 02:05 UTC, soheon-lee commented on products/views.py
> +            likes       = product.userproductlike_set.filter(user=user)
`user`가 None일 때 테스트 해보셨나요?

2021-01-20 02:05 UTC, soheon-lee commented on products/views.py
> +                'is_like'       : likes[0].is_like if likes.exists() else None,
```suggestion
                'is_like'       : likes.exist()
```
`like` 테이블에 포함되어있는 데이터 유/무 자체를 활용해서 True/False 로 통신을 해보는 것도 좋을 것 같네요 :)

2021-01-20 02:05 UTC, soheon-lee commented on users/views.py
> +                like         = likes[0]
```suggestion
                like         = likes.get()
```
요런 방법도 사용하실 수 있습니다! :) 그냥 `.get()` 하면 어떻게 동작하는지 한 번 보시고,
`.first()` 메소드와도 한 번 비교해보시면 좋습니다

2021-01-20 02:05 UTC, soheon-lee commented on users/views.py
> +            return JsonResponse({'LIKED': f"LIKED {product.name}"}, status=200)
이렇게 return이 나뉜 이유는 한 번이라도 좋아요 했던 데이터와 아닌 데이터들이 달라서 그런 것이죠?
그런데 프론트 입장에서는 그 둘을 구분하기가 어렵습니다.
한 번이라도 좋아요 했던 데이터를 다시 좋아요하는 상황인지, 새로운 아이템을 좋아요하는 것인지 눈으로 확인하고 있는 것이 아니기 때문에, 리턴 메세지를 통일하시는 것이 좋습니다 :-)

2021-01-20 04:40 UTC, FreshTuna commented on products/views.py
> +            likes       = product.userproductlike_set.filter(user=user)
login이 필수로 필요한 View라 보통의 경우에는 `None`이 되지는 않는데 login_required 데코레이터를 풀고 테스트 해보니까 `IntegrityError`가 발생하네요! ForeignKey name이 Null이 허용되지 않아 발생하는 것 같아요.

2021-01-20 04:40 UTC, FreshTuna commented on products/views.py
> +            # colors      = Colors.objects.prefetch_related('').all()
아 깜빡하고 지우지 않았네요! 감사합니닷

2021-01-20 04:41 UTC, FreshTuna commented on products/views.py
> +                          'productthickness_set__thickness','productinkcolor_set__color','product_keyword','productoption_set').get(id=product_id)
넵! 조금씩 익히고 있습니다!

2021-01-20 04:41 UTC, FreshTuna commented on users/views.py
> +                like         = likes[0]
아 넵 한번 정리해봐야겠네요! 감사합니다.

2021-01-20 04:45 UTC, FreshTuna commented on users/views.py
> +            return JsonResponse({'LIKED': f"LIKED {product.name}"}, status=200)
그렇겠네요... 둘다 통일해서 'Like' : {True 나 False}를 보내야겠네요.

2021-01-20 06:14 UTC, FreshTuna commented on products/views.py
> +                'is_like'       : likes[0].is_like if likes.exists() else None,
저희가 설계한 like 테이블에 like가 활성화 되어있는지 아닌지 판별하는 TINYINT가 존재합니다. 그래서 데이터의 유/무가 아닌 TINYINT의 값이 무엇인지가 필요합니다. 이러한 설계를 바꿔야 할까요?

2021-01-20 11:16 UTC, soheon-lee commented on users/views.py
> +            like   = UserProductLike.objects.filter(user=user, product=product).first()
```suggestion
            like    = UserProductLike.objects.filter(user=user, product=product).first()
```

2021-01-20 11:16 UTC, soheon-lee commented on users/views.py
> +        except json.decoder.JSONDecodeError:
```suggestion

            if like:
                like.is_like = not like.is_like
                like.save()
                return JsonResponse({'LIKE': like.is_like}, status=200)
            
            UserProductLike.objects.create(user=user, product=product, is_like=True)
            return JsonResponse({'LIKE': True}, status=200)
        except json.decoder.JSONDecodeError:
```
논리상 띄어쓰기가 달라지는 것이 좋을 것 같습니다

2021-01-20 11:16 UTC, soheon-lee commented on products/views.py
> +                'is_like'       : like.is_like if like else None
```suggestion
                'is_like'       : like.is_like if like else False
```

2021-01-20 14:05 UTC, FreshTuna commented on users/views.py
> +        except json.decoder.JSONDecodeError:
피드백 감사합니다!!

컨플릭도 해결했습니다 ㅎㅎ

2021-01-21 01:13 UTC, soheon-lee commented on users/views.py
> +from django.http     import JsonResponse
헙!! 충돌해결 하다가 남았네요-!

2021-01-21 01:16 UTC, soheon-lee commented
https://github.com/wecode-bootcamp-korea/tsunami-backend/pull/9#discussion_r560881925

이 리뷰 수정 안되었는데, 다시 한 번 확인 부탁드려요~

2021-01-21 02:25 UTC, FreshTuna commented on users/views.py
> +from django.http     import JsonResponse
찾아주셔서 감사합니다!

2021-01-21 02:27 UTC, FreshTuna commented on products/views.py
> +                'is_like'       : like.is_like if like else None
혹시 아직도 리뷰 반영안되었나요 ㅠㅠ 코드는 수정해서 올렸는데 다른 부분일까요..

2021-01-21 09:16 UTC, soheon-lee commented
LGTM

2021-01-21 09:17 UTC, merged